lazyreload/apps/users/urls.py
from django.urls import path
from .views import ( CreateUserAPI, LazyUpdateUserAPIView, UserListView, 
                    LoginView, LazyUserProfileView, LazyDeleteUserAPIView,
                    HomeView, AboutUsView, ContactView)

app_name = 'users'

urlpatterns = [

    path('register/', CreateUserAPI.as_view(), name="register"),
    path('login/', LoginView.as_view(), name="login"),
    path('users-list/', UserListView.as_view(), name='list-users'),
    path('userprofile/<uuid:user_id>/', LazyUserProfileView.as_view(), name = 'userprofile'),
    path('update-user/<uuid:user_id>/', LazyUpdateUserAPIView.as_view(), name='update-user'),
    path('delete-user/<uuid:user_id>/', LazyDeleteUserAPIView.as_view(), name='delete-user'),
    path('home/',HomeView.as_view(), name='home'),
    path('aboutus/',AboutUsView.as_view(), name='aboutus'),
    path('contact/',ContactView.as_view(), name='contact')
]

lazyreload/lazyreload/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

schema_view = get_schema_view(
    openapi.Info(
        title='LazyApp API',
        default_version='v1',
        description='API for Job and Flat Applications',
        terms_of_service='https://www.google.com/policies/terms/',
        contact=openapi.Contact(email='lazyapp@mail.de'),
        lincense=openapi.License(name='MIT License')
    ),
    public=True,
    permission_classes=[],
    authentication_classes=[]
)

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("apps.users.urls", namespace="users")),
    path("", include("apps.job_applications.urls", namespace="job_applications")),
    path("", include("apps.flat_applications.urls", namespace="flat_applications")),
    # swagger
    path("openapi/", schema_view.without_ui(cache_timeout=0)),
    path("swagger/", schema_view.with_ui("swagger",cache_timeout=0),name="schema-swagger-ui"),
    path("redoc/",schema_view.with_ui("redoc",cache_timeout=0),name="schema-redoc"),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS[0])

lazyreload/apps/core/models.py
from django.db import models

# Create your models here.
# class AiSettings(models.Model): # not used in CoverLetterGenerator
#     ai_setting_name = models.CharField(max_length=60, blank=False, default="new")
#     other_profile_id = models.ForeignKey("users.LazyUserProfile", on_delete=models.CASCADE)
#     # enable user to save a setting as favorite to reuse it
#     favorite = models.BooleanField(default=False,
#                                    verbose_name="Saved as Favorite")
#     # GPT temperature deterministic vs. creative
#     temperature = models.FloatField(default=0.5, verbose_name="Rational/Creative")
#     word_count = models.IntegerField(default=320, verbose_name="How long should the letter be")
#     # GPT 3.5 or 4 - high is default, for futur cost tiering
#     QUALITY_CHOICES = {
#         "low": "Low",
#         "high": "High",
#     }
#     quality = models.CharField(choices=QUALITY_CHOICES, default="high", max_length=20, blank=True)

lazyreload/apps/core/views.py
from django.shortcuts import render

# Create your views here.

lazyreload/apps/core/templates/core/aboutus.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>About Us</title>
</head>
<body>
    <div class="container">

        <header class="section-header text-center mb-5 pb-2">
          <h1>About Us</h1>
          <p>We are Iris! A team of designers, developers and digital markerters in the HNG6.0 Internship. Launched in September 2019, Iris Goal Tracker App is the first product released by Team Iris. As Mark Victor Hansen said "By recording your dreams and goals, you set in motion the process of becoming the person you most want to be..." 

        <div class="row about-cols">

          <div class="col-md-4 wow fadeInUp">
            <div class="about-col">
              <div class="img">
                <img src="img/about-mission.webp" alt="" class="img-fluid">
                <div class="icon"><i class="ion-ios-speedometer-outline"></i></div>
              </div>
              <h2 class="title"><a href="#">Our Mission</a></h2>
              <p class="text-center">
                To utilize the power of technology in setting and reaching goals...
              </p>
            </div>
          </div>

          <div class="col-md-4 wow fadeInUp" data-wow-delay="0.1s">
            <div class="about-col">
              <div class="img">
                <img src="img/about-plan.webp" alt="" class="img-fluid">
                <div class="icon"><i class="ion-ios-list-outline"></i></div>
              </div>
              <h2 class="title"><a href="#">Our Plan</a></h2>
              <p class="text-center">
               We Plan to integrate Artificial Intelligence to hitting your set targets.
              </p>
            </div>
          </div>
          
          
 <div class="col-md-4 wow fadeInUp" data-wow-delay="0.2s">
            <div class="about-col">
              <div class="img">
                <img src="img/about-vision.webp" alt="" class="img-fluid">
                <div class="icon"><i class="ion-ios-eye-outline"></i></div>
              </div>
              <h2 class="title"><a href="#">Our Vision</a></h2>
              <p class="text-center">
                To see you achieve more success in reaching more of your goals with Iris Goal Tracker.               
              </p>
            </div>
          </div>

        </div>

      </div>
</body>
</html>

lazyreload/apps/core/templates/core/contact.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Contact</title>
</head>
<body>
    <h1> Contact us page</h1>
</body>
</html>

lazyreload/apps/core/templates/core/home.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'core/lazystyle.css' %}">
    <title>LazyApp</title>
</head>
<body>
   
    <div class="container-fluid main">
      <nav class="navbar navbar-default">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span> 
            </button>
          </div>
          <div class="collapse navbar-collapse" id="myNavbar">
            <ul class="nav navbar-nav">
               <li><a href="#">Homepage</a></li>
              <li><a href="{% url 'aboutus' %}">About Us</a></li>
              <li><a href="{% url 'contact' %}">Contact Us</a></li>
              <li><a href="#">Documentation</a></li>
            </ul>
          </div>
        </div>
      </nav>
    
      <div id="homepage_pic">
         <img src="{% static 'core/images/homepage.png' %}" alt="Your Image">
      </div>
      
      <div class="covertext">
        <div class="col-lg-10" style="float:none; margin:0 auto;">
          <h1 class="title">LazyApp</h1>
          <h3 class="subtitle">Here comes a simple description</h3>
        </div>
        <div class="col-xs-12 explore">
          <a href="{% url 'login'%}"><button type="button" class="btn btn-lg explorebtn">Login</button></a>
        </div>
      </div>
    </div>

</body>
</html>
   

lazyreload/apps/core/templates/core/login.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <link rel="stylesheet" type="text/css" href="{% static 'core/lazystyle.css' %}">
</head>
<body>
    <div class="center">
        <h1> Login page </h1>
        <form method="post" action="{% url 'login' %}">
            {% csrf_token %}
            <div class="txt_field">
                <label for="username"></label>
                <input type="text" name="username" placeholder="Username" required><br>
                
            </div>
            <div class="txt_field">
                <label for="password"></label>
                <input type="password" name="password" placeholder="Password"required><br>
            </div>   
            <button type="submit" class="login-button" onclick="performLogin()"><a href="{% url 'login' %}"></a>Login</button>
            <div class="signup_link">Not a member? <a href="{% url 'users:register' %}">Sign Up</a></div>
        </form>
    </div>
    <script>
        function performLogin(){
            console.log('Logged in');
        }
    </script>
    
</body>
</html>

lazyreload/apps/core/templates/core/register.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'core/register.css' %}">
    <title>Create User</title>

    <script>
        document.addEventListener('DOMContentLoaded', function() {
            const form = document.getElementById('registrationForm');
    
            form.addEventListener('submit', function(event) {
                event.preventDefault(); 

                // Create a FormData object to hold the form data
                const formData = new FormData(form);

                // Send a POST request to the registration URL
                fetch('{% url "users:register" %}', {
                    method: 'POST',
                    headers: {
                        'X-CSRFToken': '{{ csrf_token }}',
                    },
                    body: formData,
                })
                .then(response => {
                    if (!response.ok) {
                        throw new Error('Registration failed');
                    }
                    return response.json();
                })
                .then(data => {
                    // Handle successful registration
                    console.log(data);

                    // Redirect to the login page ****
                    window.location.href = '{% url "users:login" %}';
                })
                .catch(error => {
                    // Handle registration failure
                    console.error(error.message);
                });

                fetch('{% url "users:login" %}')
                    .then(response => response.text())
                    .then(htmlContent => {
                    window.location.href = '{% url "users:login" %}'; // Redirect to the URL
                })
                .catch(error => {
                    console.error(error);
                });
            });
        });
    </script>
</head>
<body>
    <form id="registrationForm" method="post" action="{% url 'users:register' %}">
        {% csrf_token %}
        <div class="wrapper">
            <div class="signup">
                <h1>Sign Up</h1>
                <fieldset>
                    <label>First Name</label>
                    <input type="text" name="first_name" placeholder="First Name" required>
                    <label>Last Name</label>
                    <input type="text" name="last_name" placeholder="Last Name" required>
                    <label>Username</label>
                    <input type="text" name="username" placeholder="Username" required>
                </fieldset>
                <fieldset>
                    <label>Email</label>
                    <input type="email" name="email" placeholder="Email" required>
                </fieldset>
                <fieldset>
                    <label>Password</label>
                    <input type="password" name="password" placeholder="Password" required>
                </fieldset>
                <button type="submit" class="register-button">Register</button>
            </div>  
        </div>
    </form>
</body>
</html> 

lazyreload/apps/core/templates/core/userprofile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dashboard</title>
</head>
<body>
    <h1>Welcome Page</h1>

    <div>
        <p>Welcome {{ username }}!</p>
    </div>
</body>
</html>